import type { AppMode } from '@/composables/useAppMode'
import type { UserRole } from '@/composables/useRole'

export { DOMAIN_VOCABULARY, getTermsForRole } from './vocabulary'
export type { DomainTerm } from './vocabulary'
export { STANDARD_RULES, getRulesForRole } from './standards'
export type { StandardRule } from './standards'
export { getAspiceProfile } from './aspice'
export type { AspiceProfile, AspiceMapping, AspiceSuggestion } from './aspice'
export { buildConflictCheckPrompt } from './conflicts'
export { buildTraceSuggestPrompt } from './trace-suggest'
export { buildImpactAnalysisPrompt } from './trace-impact'
export { REVIEW_PERSPECTIVES, buildDeepReviewPrompt } from './review-perspectives'
export type { ReviewPerspective } from './review-perspectives'
export type { ReviewStatus, ReviewStep, ChecklistItem, TraceabilityGap } from './types'
export type { RequirementLevel } from './traceability.design'
export * from './mode-config'
